# Generated by Django 2.2 on 2019-04-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190414_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='topingPrice',
            field=models.FloatField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='largePrice',
            field=models.FloatField(max_length=7),
        ),
        migrations.AlterField(
            model_name='menu',
            name='smallPrice',
            field=models.FloatField(max_length=7),
        ),
    ]
