# Generated by Django 2.2 on 2019-04-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190415_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='topingPrice',
            new_name='toppingPrice',
        ),
    ]
