# Generated by Django 2.2 on 2019-04-15 03:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190415_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='addOns',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
